### PR TITLE
jquery: Add jquery as env

### PR DESCRIPTION
**Pull request by ghost**
I think it will be better to use
```json
env: {
    "jquery": true
}
```
Instead of 
```json
globals: {
    "$": false
}
```
Docs:
https://eslint.org/docs/user-guide/configuring#specifying-environments

### CODE REVIEW

**Comment by jdforrester** [comment]
We did this intentionally as the `jQuery` global is being removed in MediaWiki code in lieu of `$`.

**Comment by ghost** [comment]
@jdforrester sorry then :(

**Comment by jdforrester** [comment]
Totally understandable, it's an oddity and it's undocumented. Thanks for the suggestion though. :-)

**Comment by edg2s** [comment]
More details here: https://phabricator.wikimedia.org/T208951

**Pull request closed without merging**
