### PR TITLE
Release v0.20.0

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by edg2s** [comment]
Merge after #375

**Comment by jdforrester** [comment]
Do we want to pull in the new eslint-plugin-no-jquery first?

**Comment by jdforrester** [comment]
Not before #377.

**Review by jdforrester — CHANGES_REQUESTED** [review]
Need to mention the jquery change.

(Also, should we replicate the upstream things like "Rule fix: Add fixer for `no-on-ready`"?)

**Comment by edg2s** [comment]
> (Also, should we replicate the upstream things like "Rule fix: Add fixer for `no-on-ready`"?)

I haven't done in the past. Unless it's significant, in which case it could be mentioned in the library update commit.

**Review by jdforrester — APPROVED** [review]
Ack.

**Pull request merged**
