### PR TITLE
Changed rule: valid-jsdoc — Set preferred cases for types

### PR DESCRIPTION
**Pull request by niedzielski**
This patch specifies that lowercase types are preferred for boolean,
number, string, undefined, and null primitives, and uppercase for
Objects, Arrays, Functions, Dates, RegExps, and Errors which matches the
typing convention on wiki:

https://www.mediawiki.org/wiki/Manual:Coding_conventions/JavaScript#Types

### CODE REVIEW

**Comment by niedzielski** [comment]
@jdlrobson, I can't seem to add you to this review but please check it out!

**Comment by jdforrester** [comment]
Nice improvement!

**Review by Krinkle — CHANGES_REQUESTED** [review]
@niedzielski Could you add positive and negative tests for these as well?

**Comment by niedzielski** [comment]
@Krinkle, sure. Tests added :+1:

**Review by Krinkle — APPROVED** [review]

**Pull request merged**
