### PR TITLE
common: Also inherit from plugin:security/recommended

### PR DESCRIPTION
**Pull request by jdforrester**
Fixes https://phabricator.wikimedia.org/T328568.

### CODE REVIEW

**Review by sbassett29 — DISMISSED** [review]
LGTM, thanks.  I'm hoping eslint-plugin-security doesn't become too noisy, but I suppose we can see how it performs on a few more js codebases.

**Comment by jdforrester** [comment]
> LGTM, thanks. I'm hoping eslint-plugin-security doesn't become too noisy, but I suppose we can see how it performs on a few more js codebases.

I think `security/detect-object-injection` is likely to be the noisiest in general. In a test run on OOUI, VE, and MW core, I got 449, 416, and 1053 new warnings, of which 408, 396, and 992 are just this one. 

In practice, LibraryUpgrader will switch all repos over, downgrading errors to warning as appropriate, but it may create a lot of noise across the codebase estate, hiding other warnings.

**Comment by sbassett29** [comment]
@edg2s - Any chance of a review/merge for this?  Should be fairly straight-forward, thanks.

**Comment by edg2s** [comment]
> > LGTM, thanks. I'm hoping eslint-plugin-security doesn't become too noisy, but I suppose we can see how it performs on a few more js codebases.
> 
> I think `security/detect-object-injection` is likely to be the noisiest in general. In a test run on OOUI, VE, and MW core, I got 449, 416, and 1053 new warnings, of which 408, 396, and 992 are just this one.
> 
> In practice, LibraryUpgrader will switch all repos over, downgrading errors to warning as appropriate, but it may create a lot of noise across the codebase estate, hiding other warnings.

This seems like too much warning noise. I'd rather we start with a smaller subset of more reliable rules.

**Comment by sbassett29** [comment]
> This seems like too much warning noise. I'd rather we start with a smaller subset of more reliable rules.

Ok.  If we removed the `security/detect-object-injection` rule, I think that would likely address your concerns.  I do think there is some value here in running these security checks in CI once noisier rules are eliminated.

**Comment by edg2s** [comment]
The repo's description describe this plug as "ESLint rules for Node Security", do they have much value in the client?

**Comment by sbassett29** [comment]
> The repo's description describe this plug as "ESLint rules for Node Security", do they have much value in the client?

So the aforementioned `security/detect-object-injection` rule, while perhaps too noisy and fairly low-risk most of the time, IMO, is absolutely relevant for both NodeJS and client-side JS.  One can see the other rules here and on github:

https://www.npmjs.com/package/eslint-plugin-security

While a couple are fairly Node-specific (expressjs, etc.) the ones dealing with bi-directional characters, eval, regexps, etc. are certainly relevant to both NodeJS and client-side JS.

**Comment by sbassett29** [comment]
I don't have perms to modify PRs for this repo, but disabling `security/detect-object-injection` should look something like the attached patch file.  I think this would eliminate most of the noise from `eslint-plugin-security`, while preserving some valuable security rules.  It would be really nice if we could merge this and at least see how it performs in CI.
[pr490update.patch](https://github.com/wikimedia/eslint-config-wikimedia/files/10972028/pr490update.patch)

**Comment by jdforrester** [comment]
> I don't have perms to modify PRs for this repo, but disabling `security/detect-object-injection` should look something like the attached patch file. I think this would eliminate most of the noise from `eslint-plugin-security`, while preserving some valuable security rules. It would be really nice if we could merge this and at least see how it performs in CI. [pr490update.patch](https://github.com/wikimedia/eslint-config-wikimedia/files/10972028/pr490update.patch)

Oh, sorry about that; I've tweaked and re-based the patch. Does this look good to you to land?

**Comment by sbassett29** [comment]
> Oh, sorry about that; I've tweaked and re-based the patch. Does this look good to you to land?

No problem, lgtm!

**Review by catrope — APPROVED** [review]

**Pull request merged**
