### PR TITLE
Introduce eslint-plugin-jquery and create wikimedia/jquery ruleset

### LINKED ISSUE #106: Consider rules from eslint-plugin-jquery
https://github.com/dgraham/eslint-plugin-jquery allows disabling certain jQuery functions where faster native alternatives are available.

For example we could disable `$.inArray` as all our compatible browsers support `[].indexOf`.

### PR DESCRIPTION
**Pull request by edg2s**
Fixes #106

### CODE REVIEW

**Comment by Krinkle** [comment]
LGTM. I think we can postpone the decision on browser/nodejs vs es5/es6 presets for a later time and get this out first.

**Review by Krinkle — APPROVED** [review]

**Comment by jdforrester** [comment]
I disagree.

**Comment by Krinkle** [comment]
Hm.. well, I don't mind the overhead of a few extra rules that would otherwise be ignored and harmless.

But, I am noticing something that might become more inconvenient, which is that due to being part of the default preset, it means projects will have to install the jquery plugin as peer dependency when upgrading, which isn't the case for qunit, so we may want to avoid that.

I've drafted a proposal at https://github.com/wikimedia/eslint-config-wikimedia/issues/106#issuecomment-429054694 that could resolve this.

**Comment by edg2s** [comment]
Amended, this now creates an optional wikimedia/jquery ruleset.

**Comment by jdforrester** [comment]
This is going to be a nightmare to rebase #109 onto, but is pretty easy to rebase this onto that…

**Comment by edg2s** [comment]
Well if you're volunteering...

**Comment by jdforrester** [comment]
> Well if you're volunteering...

I am, but I've had not one byte of feedback on 109 yet. ;-P

**Comment by edg2s** [comment]
I'll rebase them the other way if you merge this one.

**Review by jdforrester — APPROVED** [review]
Weren't we going to use eslint-plugin-jquery from the Wikimedia repo?

**Comment by jdforrester** [comment]
Blocked on https://github.com/wikimedia/eslint-plugin-jquery/issues/5 AIUI.

**Review by jdforrester — APPROVED** [review]

**Pull request merged**
