### PR TITLE
Fix typo in test

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Review by catrope — APPROVED** [review]

**Comment by jdforrester** [comment]
The possessive was right; why was it removed? This now reads as very poor English.

**Comment by edg2s** [comment]
meh - feel free to fix (and in stylelint-config-wikimedia), I'm not bothered

**Comment by edg2s** [comment]
(I copied @Krinkle's patch from there)

**Comment by jdforrester** [comment]
Ah. Ack. Will do.

**Pull request merged**
